# Generated by Django 3.0.3 on 2020-05-14 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("software", "0002_auto_20200514_0546"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog", name="content", field=models.TextField(),
        ),
    ]
